# Generated by Django 3.2.9 on 2022-06-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeDelivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='',
            new_name='new_user',
        ),
    ]
