# Generated by Django 4.1.5 on 2023-08-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeDelivery', '0003_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='new_user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='new_user',
            name='pin',
        ),
    ]
